name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish Code as Github Package - ${{ inputs.version }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Permissions
        run: chmod +x gradlew

      - name: Publish
        run: ./gradlew :publish
        env:
          VERSION: ${{ inputs.version }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
